# Generated by Django 5.1.3 on 2024-11-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
